version: '3'
services:
  elk:
    image: "sebp/elk"
    ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
    volumes:
    - ./nginx_logstash.conf:/etc/logstash/conf.d/11-nginx.conf
    - ./nginx_template.json:/templates/nginx_template.json
    - ./elasticsearch_data:/var/lib/elasticsearch
    restart: unless-stopped
